//
//  CefVersion.h
//  CefViewCore
//
//  Created by Sheen Tian on 2025/1/19.
//  This file was generated during CMake configuring.
//  Do not edit this file directly by manual.
//  Edit the CefVersion.h.in and then re-config project with CMake.
//

#ifndef CefVersion_h
#define CefVersion_h
#pragma once

// clang-format off
#define CEF_VERSION "122.1.13+gde5b724+chromium-122.0.6261.130"
#define CEF_VERSION_MAJOR 122
#define CEF_VERSION_MINOR 1
#define CEF_VERSION_PATCH 13
#define CEF_COMMIT_NUMBER 2925
#define CEF_COMMIT_HASH "de5b72441ba5194c72e38628c85bfab7d7e4918e"
// clang-format on

#endif // CefVersion
